### ISSUE TITLE
Letsencrypt certificate expired

### ISSUE THREAD

**Issue by sneumann** [edamontology/edamontology.org#2]
Hi,

the Letsencrypt certificate for https://edamontology.org/topic_3070
has expired two years ago, any way to kick that into working again ?
Any place where I can open that as an (github) issue ? 

Yours, 
Steffen

**Comment by joncison** [comment]
Hi @matuskalas  - please take a look, thanks !

**Comment by matuskalas** [comment]
This is a known issue, and can't be solved immediately.

Please use http://edamontology.org instead of HTTPS

**Comment by sneumann** [comment]
Yes, will do, but I suggest to keep the issue open. Yours, Steffen

**Comment by matuskalas** [comment]
Sure, we need to fix it, it's been a shame.
I'll push onto the higher instances...

**Comment by matuskalas** [comment]
Was fixed in the Northern summer of 2020, finally!
(There was a need to move to a new, up-to-date server, which finally happened)
